### ISSUE TITLE
GetCurrentUserInfo is throw before loading info completed

### ISSUE THREAD

**Issue by neungkl** [we-inc/mms-snow-white-and-the-seven-pandas#160]
There are some strange behavior in file `user.service.ts`

```javascript
getCurrentUserInfo(): UserInfo | undefined {
  let currentUserInfo;
  let isInitialized = false;

  this.userInfo.subscribe(userInfo => {
    currentUserInfo = userInfo;
    isInitialized = true;
  }).unsubscribe();

  if (!isInitialized) {
    throw new Error('Cannot get current UserInfo: userInfo is not available yet');
  }

  return currentUserInfo;
}
``` 

Sometimes when I test my code, it shows the `Cannot get current UserInfo: userInfo is not available yet` exception. I think the `userInfo.subscribe` should be synchronous.

To make sure, I try to add some delays in `getInitialUserInfo()` and this error is reproduce.

**Comment by futurizing** [comment]
It's the expected behavior, as it's the **current** value. The method might not be clear (sorry!) You should depend on this method when you want to use the current userInfo locally, which might be outdated. If you want the latest userInfo, please create a new method that call the API directly. (maybe rename + comment the old one to prevent confusion).
